export enum ProcessEnum {
  MUST_GET_AUDIO_REQUIREMENT,
  MUST_TURN_AUDIO_REQUIREMENT_INTO_STRING_REQUIREMENT,
  MUST_GET_RUO_FROM_STRING_REQUIREMENT,
  MUST_RUN_STRATEGY_CONTEXT_WITH_RUO_AND_STRING_REQUIREMENT,
}
