import LayerFooter from '@/components/layers/layer-footer/layer-footer'
import LayerHeader from '@/components/layers/layer-header/layer-header'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <LayerHeader />
      {children}
      <LayerFooter />
    </>
  )
}
